services:
    php:
        container_name: frankenphp
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
        restart: always
        ports:
            - 80:80
        volumes:
            - ./php:/app/public
        tty: true
