FROM dunglas/frankenphp

ENV SERVER_NAME=http://localhost
# ENV MERCURE_PUBLIC_URL=http://localhost/.well-known/mercure
# ENV APP_RUNTIME=Runtime\\FrankenPhpSymfony\\Runtime
# ENV FRANKENPHP_CONFIG="worker ./public/index.php"
